# Generated by Django 6.0.7 on 2026-07-09 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentterrainrating',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'is_agent_terrain': True}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentterrainrating',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_donnees_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantreview',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_logements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantreview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantreview',
            unique_together={('property', 'locataire')},
        ),
    ]
