# Generated by Django 6.0.7 on 2026-07-09 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_visite', models.DateTimeField()),
                ('statut', models.CharField(choices=[('demandee', 'Demandée'), ('confirmee', 'Confirmée'), ('effectuee', 'Effectuée'), ('annulee', 'Annulée')], default='demandee', max_length=20)),
                ('frais_deplacement_contribues', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_a_effectuer', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='properties.property')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_reservees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_visite'],
            },
        ),
    ]
