# Generated by Django 6.0.7 on 2026-07-09 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('type_compteur', models.CharField(choices=[('individuel', 'Individuel'), ('partage', 'Partagé')], max_length=20)),
                ('type_alimentation', models.CharField(choices=[('cash_power', 'CASH POWER'), ('classique', 'Compteur classique')], max_length=20)),
                ('derniere_facture_sonabel', models.FileField(blank=True, help_text='Obligatoire si compteur classique', null=True, upload_to='logements/factures_sonabel/')),
                ('montant_moyen_redevance', models.DecimalField(blank=True, decimal_places=0, help_text='Obligatoire si CASH POWER', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('nouveau_prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('justification', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_logement', models.CharField(choices=[('studio', 'Studio'), ('chambre_salon', 'Chambre-salon'), ('appartement', 'Appartement'), ('villa', 'Villa'), ('maison_cour_commune', 'Maison / Cour commune'), ('autre', 'Autre')], max_length=30)),
                ('prix', models.DecimalField(decimal_places=0, help_text='Prix réel demandé par le bailleur (FCFA)', max_digits=12)),
                ('conditions_location', models.TextField(help_text='Conditions de location (avance, durée min., etc.)')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('surface_m2', models.DecimalField(decimal_places=2, help_text='Surface en m²', max_digits=8)),
                ('acces_goudron', models.BooleanField(default=False, help_text='Accès direct à une route bitumée')),
                ('is_verified', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, help_text='Vidéo complète du logement')),
                ('commission_kasa_pourcentage', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logements/photos/')),
                ('piece', models.CharField(blank=True, help_text='Ex: Chambre 1, Cuisine, Salon', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('arrondissement', models.CharField(blank=True, max_length=100)),
                ('boundary_geojson', models.JSONField(blank=True, help_text='Polygone GeoJSON des limites du quartier', null=True)),
                ('arrondissement_boundary_geojson', models.JSONField(blank=True, help_text="Polygone GeoJSON des limites de l'arrondissement", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('type_compteur', models.CharField(choices=[('individuel', 'Individuel'), ('partage', 'Partagé')], max_length=20)),
                ('derniere_facture_onea', models.FileField(upload_to='logements/factures_onea/')),
                ('frequence_coupures', models.CharField(blank=True, help_text='Fréquence des coupures signalée par les anciens locataires', max_length=255)),
            ],
        ),
    ]
