# Generated by Django 6.0.7 on 2026-07-09 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='agent_terrain',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_agent_terrain': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logements_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='bailleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logements_proposes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='properties.property'),
        ),
        migrations.AddField(
            model_name='electricityinfo',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_info', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='quartier',
            unique_together={('nom', 'ville')},
        ),
        migrations.AddField(
            model_name='property',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logements', to='properties.quartier'),
        ),
        migrations.AddField(
            model_name='waterinfo',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_info', to='properties.property'),
        ),
    ]
