# Generated by Django 6.0.7 on 2026-07-09 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeDepositSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cotisation_mensuelle', models.DecimalField(decimal_places=0, max_digits=10)),
                ('nombre_mensualites_prevues', models.PositiveSmallIntegerField(default=12)),
                ('montant_verse', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revenu_mensuel', models.DecimalField(decimal_places=0, max_digits=12)),
                ('loyer_min_recommande', models.DecimalField(decimal_places=0, editable=False, max_digits=12)),
                ('loyer_max_recommande', models.DecimalField(decimal_places=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositSavings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_cible', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_epargne', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_cours', 'Épargne en cours'), ('complete', 'Caution complète'), ('restituee', 'Restituée au locataire'), ('retenue', 'Retenue (dégâts constatés)')], default='en_cours', max_length=20)),
                ('montant_restitue', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('motif_retenue', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('loyer_mensuel', models.DecimalField(decimal_places=0, max_digits=12)),
                ('utilise_caution_alternative', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('document_url', models.URLField(blank=True, help_text='Lien vers le contrat formalisé (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mois', models.DateField(help_text='Premier jour du mois concerné')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-mois'],
            },
        ),
    ]
