# Generated by Django 6.0.7 on 2026-07-09 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsimulation',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations_budget', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='properties.property'),
        ),
        migrations.AddField(
            model_name='depositsavings',
            name='contrat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epargne_caution', to='finance.rentalcontract'),
        ),
        migrations.AddField(
            model_name='alternativedepositsubscription',
            name='contrat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotisation_alternative', to='finance.rentalcontract'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.rentalcontract'),
        ),
        migrations.AlterUniqueTogether(
            name='rentpayment',
            unique_together={('contrat', 'mois')},
        ),
    ]
