# Generated by Django 6.0.7 on 2026-07-09 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='metier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artisans', to='artisans.metier'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='metier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='artisans.metier'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='artisans.artisanprofile'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_service', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='metier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='artisans.metier'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artisans.prestation'),
        ),
        migrations.AddField(
            model_name='servicepayment',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='artisans.servicerequest'),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='artisans.servicerequest'),
        ),
    ]
