# Generated by Django 6.0.7 on 2026-07-09 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_signalement', models.CharField(choices=[('prix_non_justifie', 'Changement de prix non justifié'), ('conditions_changees', 'Changement des conditions de location'), ('fausse_annonce', 'Fausse annonce'), ('absence_eau', "Absence d'eau"), ('absence_courant', 'Absence de courant'), ('securite', 'Problème de sécurité')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='ouvert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
